/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AvatarUI.java
 *
 * Created on Feb 24, 2011, 11:02:09 PM
 */

package probeIt.ui.avatar;

import javax.swing.*;
import java.util.*;
import java.awt.*;
import probeIt.ui.avatar.video.*;

/**
 *
 * @author paulo
 */
public class ProbeItAvatar extends java.awt.Frame {

    public static ProbeItAvatar instance;
    private Vector<String> answers;

    public static ProbeItAvatar getInstance() {
       if(instance == null)
           instance = new ProbeItAvatar();
       return instance;
    }

    /** Creates new form AvatarUI */
    public ProbeItAvatar() {
        instance = this;
        initComponents();
        //setAvatar(ProbeItAvatar.oracle);
        clearAnswers();
   }

    public void setAnswers(Vector<String> ans) {
        answers = ans;
        jList2.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return answers.size(); }
            public Object getElementAt(int i) { return answers.elementAt(i); }
        });   
    }

    public void clearAnswers() {
        setAnswers(new Vector<String>());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        avatarPanel = new AvatarView(false);

        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setBackground(java.awt.Color.lightGray);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.add(avatarPanel);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(2000, 1000));

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        jPanel4.add(jScrollPane3);

        add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /*
     * This method identifies that the user has asked for a question. The
     * number of the selection is returned to the appropriate avatar who is
     * going to addressing the request.
     */
    private void questionPanelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_questionPanelValueChanged
        Comments.clear();
        //int selectedIndex = questionPanel.getSelectedIndex();
        //currentAvatar.performQuestion(selectedIndex);
    }//GEN-LAST:event_questionPanelValueChanged


    /*
     * From the answers of the browser, the method select the returned value
     * either as the name of a publication or product.
     *
     */
    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
        //System.out.println(evt.getSource().toString());
        //System.out.println("Type: " + answerType);
        if (evt.getSource() != null) {
            JList list = (JList)(evt.getSource());
            if (list.getSelectedValue() != null) {
                String selection = list.getSelectedValue().toString();
                avatarPanel.setSelection(selection);
            }
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void avatarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avatarNameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProbeItAvatar().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel4;
    private AvatarView avatarPanel;
    private javax.swing.JScrollPane jScrollPane3;
    
    // End of variables declaration//GEN-END:variables

}
