
package cacher;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "VisCacheServiceService", targetNamespace = "http://cacher/", wsdlLocation = "http://iw.cs.utep.edu/VisCacheAccess/VisCacheService?wsdl")
public class VisCacheServiceService
    extends Service
{

    private final static URL VISCACHESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cacher.VisCacheServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cacher.VisCacheServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://iw.cs.utep.edu/VisCacheAccess/VisCacheService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://iw.cs.utep.edu/VisCacheAccess/VisCacheService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VISCACHESERVICESERVICE_WSDL_LOCATION = url;
    }

    public VisCacheServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VisCacheServiceService() {
        super(VISCACHESERVICESERVICE_WSDL_LOCATION, new QName("http://cacher/", "VisCacheServiceService"));
    }

    /**
     * 
     * @return
     *     returns VisCacheService
     */
    @WebEndpoint(name = "VisCacheServicePort")
    public VisCacheService getVisCacheServicePort() {
        return super.getPort(new QName("http://cacher/", "VisCacheServicePort"), VisCacheService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VisCacheService
     */
    @WebEndpoint(name = "VisCacheServicePort")
    public VisCacheService getVisCacheServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cacher/", "VisCacheServicePort"), VisCacheService.class, features);
    }

}
